{{ config
(
    materialized='table',
    database = 'PROD',
    schema = 'DATA_QC'
)
}}

with on_prem_auto as (
select distinct
trim(split_part(opp.customer,'-',0)) as CUSTOMER,
opp.DATE,
opp.NUMBER_OF_ARCHIVED_LAYOUTS,
opp.NUMBER_OF_ARCHIVED_RELEASES,
opp.NUMBER_OF_CHARACTERS_COMPLETED,
opp.NUMBER_OF_CORRECT_MACHINE_PREDICTED_NON_STRUCTURED_PAGES,
opp.NUMBER_OF_DOCUMENTS_COMPLETED,
opp.NUMBER_OF_DOCUMENTS_CREATED,
opp.NUMBER_OF_FIELDS_COMPLETED,
opp.NUMBER_OF_FIELDS_CREATED,
opp.NUMBER_OF_FIELDS_EXTRACTED_IN_CUSTOM_SUPERVISION,
opp.NUMBER_OF_FIELDS_EXTRACTED_IN_FLEXIBLE_EXTRACTION,
opp.NUMBER_OF_FIELDS_MACHINE_IDENTIFIED,
opp.NUMBER_OF_FIELDS_MACHINE_TRANSCRIBED,
opp.NUMBER_OF_FIELDS_MANUALLY_IDENTIFIED,
opp.NUMBER_OF_FIELDS_MANUALLY_TRANSCRIBED,
opp.NUMBER_OF_FILES_SUBMITTED,
opp.NUMBER_OF_INCORRECT_MACHINE_PREDICTED_NON_STRUCTURED_PAGES,
opp.NUMBER_OF_INCREMENTAL_FIELDS_MACHINE_TRANSCRIBED,
opp.NUMBER_OF_LAYOUT_VERSIONS,
opp.NUMBER_OF_LAYOUTS,
opp.NUMBER_OF_LIVE_LAYOUTS,
opp.NUMBER_OF_PAGES_CLASSIFIED_AUTOMATICALLY,
opp.NUMBER_OF_PAGES_CLASSIFIED_MANUALLY,
opp.NUMBER_OF_PAGES_COMPLETED,
opp.NUMBER_OF_PAGES_CREATED,
opp.NUMBER_OF_PAGES_MATCHED_TO_FLEX_LAYOUTS_COMPLETED,
opp.NUMBER_OF_PAGES_MATCHED_TO_FLEX_LAYOUTS_CREATED,
opp.NUMBER_OF_PAGES_MATCHED_TO_FORM_LAYOUTS_COMPLETED,
opp.NUMBER_OF_PAGES_MATCHED_TO_FORM_LAYOUTS_CREATED,
opp.NUMBER_OF_PAGES_WITH_FIELDS_ON_THEM_COMPLETED,
opp.NUMBER_OF_PAGES_WITH_FIELDS_ON_THEM_CREATED,
opp.NUMBER_OF_QA_CORRECT_RESPONSES_ON_MACHINE_FIELD_IDENTIFICATION,
opp.NUMBER_OF_QA_CORRECT_RESPONSES_ON_MACHINE_TRANSCRIPTION,
opp.NUMBER_OF_QA_CORRECT_RESPONSES_ON_MANUAL_FIELD_IDENTIFICATION,
opp.NUMBER_OF_QA_CORRECT_RESPONSES_ON_MANUAL_TRANSCRIPTION,
opp.NUMBER_OF_QA_CORRECT_RESPONSES_ON_SYSTEM_FIELD_IDENTIFICATION,
opp.NUMBER_OF_QA_CORRECT_RESPONSES_ON_SYSTEM_TRANSCRIPTION,
opp.NUMBER_OF_QA_RESPONSES_ON_MACHINE_FIELD_IDENTIFICATION,
opp.NUMBER_OF_QA_RESPONSES_ON_MACHINE_TRANSCRIPTION,
opp.NUMBER_OF_QA_RESPONSES_ON_MANUAL_FIELD_IDENTIFICATION,
opp.NUMBER_OF_QA_RESPONSES_ON_MANUAL_TRANSCRIPTION,
opp.NUMBER_OF_QA_RESPONSES_ON_SYSTEM_FIELD_IDENTIFICATION,
opp.NUMBER_OF_QA_RESPONSES_ON_SYSTEM_TRANSCRIPTION,
opp.NUMBER_OF_RELEASE_DEPLOYS,
opp.NUMBER_OF_RELEASES,
opp.NUMBER_OF_SUBMISSIONS_COMPLETED,
opp.NUMBER_OF_SUBMISSIONS_CREATED,
opp.NUMBER_OF_TABLE_CELLS_COMPLETED,
opp.NUMBER_OF_TABLE_CELLS_CREATED,
opp.NUMBER_OF_TABLE_CELLS_EXTRACTED_IN_FLEXIBLE_EXTRACTION,
opp.NUMBER_OF_TABLE_CELLS_MACHINE_IDENTIFIED,
opp.NUMBER_OF_TABLE_CELLS_MANUALLY_IDENTIFIED,
opp.NUMBER_OF_UNIQUE_LAYOUTS_MATCHED,
opp.ORGANIZE_DOCUMENTS_NUMBER_OF_DOCUMENTS_CREATED_IN_STEP_1,
opp.ORGANIZE_DOCUMENTS_NUMBER_OF_DOCUMENTS_OUTPUTTED_IN_STEP_1,
opp.ORGANIZE_DOCUMENTS_NUMBER_OF_FOLDERS_CREATED_IN_STEP_2,
opp.ORGANIZE_DOCUMENTS_NUMBER_OF_PAGES_CATEGORIZED_IN_STEP_1,
opp.ORGANIZE_DOCUMENTS_NUMBER_OF_PAGES_SHOWN_IN_STEP_1,
opp.ORGANIZE_DOCUMENTS_NUMBER_OF_TASKS_PERFORMED,
opp.QA_CORRECT_RESPONSES_ON_MACHINE_NON_STRUCTURED_CLASSIFICATION,
opp.QA_CORRECT_RESPONSES_ON_MANUAL_NON_STRUCTURED_CLASSIFICATION,
opp.QA_CORRECT_RESPONSES_ON_SYSTEM_NON_STRUCTURED_CLASSIFICATION,
opp.QA_RESPONSES_ON_MACHINE_NON_STRUCTURED_CLASSIFICATION,
opp.QA_RESPONSES_ON_MANUAL_NON_STRUCTURED_CLASSIFICATION,
opp.QA_RESPONSES_ON_SYSTEM_NON_STRUCTURED_CLASSIFICATION,
opp.SEATS,
opp.SOFTWARE_VERSION,
opp.environment_id
from RAW.USAGE_REPORTING.ON_PREM_PROD as opp 
left join FIVETRAN_DATABASE.SALESFORCE.INSTANCE_C as sfdc on (sfdc.id = opp.environment_id) 
),

sfdc as (
select distinct
id,
name,
is_deleted,
created_date,
type_c,
instance_group_c,
fqdn_c
from FIVETRAN_DATABASE.SALESFORCE.INSTANCE_C
where _fivetran_deleted = false
),

fct_combined_int as (
select distinct
sfdc.name as sfdc_license_key_name ,
sfdc.id as environment_id,
sfdc.is_deleted,
sfdc.created_date,
sfdc.type_c as environment_type,
sfdc.instance_group_c as instance_group,
sfdc.fqdn_c as fqdn,
opa.date,
opa.customer,
sum(opa.NUMBER_OF_PAGES_CREATED) as total_pages
from sfdc 
left join on_prem_auto as opa on (sfdc.id = opa.environment_id)
group by all
),

fct_combined as (
select distinct
sfdc_license_key_name,
environment_id,
date(created_date) as license_key_create_date,
environment_type,
instance_group,
fqdn,
customer,
sum(total_pages) over (partition by sfdc_license_key_name, environment_id, environment_type, instance_group, fqdn, customer) as total_pages_processed,
max(date) over (partition by sfdc_license_key_name, environment_id, environment_type, instance_group, fqdn, customer) as latest_day_receiving_usage
from fct_combined_int
)

select * from fct_combined 
order by customer, environment_type