name: 'tiktok_ads'
version: '0.1.1'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  tiktok_ads:
    +schema: tiktok_ads
    +materialized: table
    intermediate:
      +materialized: ephemeral
vars:
  tiktok_ads:
    ad_history: "{{ ref('stg_tiktok_ads__ad_history') }}"
    ad_group_history: "{{ ref('stg_tiktok_ads__ad_group_history') }}"
    campaign_history: "{{ ref('stg_tiktok_ads__campaign_history') }}"
    advertiser: "{{ ref('stg_tiktok_ads__advertiser') }}"
    ad_report_hourly: "{{ ref('stg_tiktok_ads__ad_report_hourly') }}"
    campaign_report_hourly: "{{ ref('stg_tiktok_ads__campaign_report_hourly') }}"
    ad_group_hourly: "{{ ref('stg_tiktok_ads__ad_group_report_hourly') }}"
    
